# Generated by Django 5.1.6 on 2025-03-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopse', models.TextField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('duracao', models.CharField(max_length=255)),
                ('diretor', models.CharField(max_length=255)),
                ('ano', models.CharField(max_length=255)),
                ('faixa_etaria', models.CharField(choices=[('L', 'Livre'), ('10', '10 anos'), ('12', '12 anos'), ('14', '14 anos'), ('16', '16 anos'), ('18', '18 anos')], max_length=2)),
            ],
        ),
    ]
